export const apiData = {
    serianNo: "123456",
    macId: 123456,
    firmwareVersion: 1.12,
    softwareVersion: "Erretgf22323",
    library: "Wetewrt rtur",
    systemInfo: [
      {
        activatedModules: "Engine",
        numberOfLicence: "2",
        licenceNumber: "AGF146789",
        expiryDate: "18 Oct 2023",
        isLocked: false,
      },
      {
        activatedModules: "Turbo",
        numberOfLicence: "2",
        licenceNumber: "YUO87659",
        expiryDate: "18 Oct 2023",
        isLocked: false,
      },
      {
        activatedModules: "Motor",
        numberOfLicence: "2",
        licenceNumber: "OPL875432",
        expiryDate: "18 Oct 2023",
        isLocked: false,
      },
      {
        activatedModules: "Torque",
        numberOfLicence: "2",
        licenceNumber: "KHL095278",
        expiryDate: "18 Oct 2023",
        isLocked: false,
      },
      {
        activatedModules: "Bearing",
        numberOfLicence: "2",
        licenceNumber: "TYU8916736",
        expiryDate: "18 Oct 2023",
        isLocked: false,
      },
      {
        activatedModules: "Compressor",
        numberOfLicence: "2",
        licenceNumber: "AGF146789",
        expiryDate: "18 Oct 2023",
        isLocked: true,
      },
      {
        activatedModules: "Turbine",
        numberOfLicence: "2",
        licenceNumber: "AGF146789",
        expiryDate: "18 Oct 2023",
        isLocked: true,
      },
      {
        activatedModules: "Engine",
        numberOfLicence: "2",
        licenceNumber: "AGF146789",
        expiryDate: "18 Oct 2023",
        isLocked: true,
      },
    ],
  };